# syntax=docker/dockerfile:1
FROM ubuntu:18.04
RUN apt-get update 
RUN apt-get install -y git 
RUN apt-get install -y python3.9
RUN apt-get install -y python3-pip
RUN apt-get install -y net-tools
RUN apt-get install -y vim
RUN apt-get install -y iputils-ping
RUN apt-get install -y curl
RUN python3.9 -m pip install pip
RUN python3.9 -m pip install MarkupSafe==2.0.0 
RUN python3.9 -m pip install flask pika pymysql uuid requests Flask-JSGlue flask_cors pydantic bson flask_restful
EXPOSE 3320
